POST http://127.0.0.1:8080/task/
Content-Type: application/json

{
  "images": [
    {
      "image": "https://www.rockauto.com/info/768/768_ULTRAPOWER STANDARD MOTOR PRODUCTS_B75001_2.jpg",
      "crop": false
    }
  ]
}

###
GET http://127.0.0.1:8080/task/?taskid=5577006791947779410
Content-Type: application/json

###

POST http://img.gt-shop.ru:3008/task/
Content-Type: application/json

{
  "images": [
    {
      "url": "https://gt-shop.ru/images/w600/newdata/amobuc.bmf.xl.jpg",
      "crop": false
    }
  ]
}

###
GET http://127.0.0.1:8080/status/
Accept: application/json

###

