version: '3'
services:
  service:
    restart: always
    build: ./upload/
    ports:
      - "3008:8080"
    volumes:
      - ./images/:/upload/
    logging:
      driver: none
    environment:
      CHECK_URL: "https://www.rockauto.com/"