version: '3.3'
services:
  service:
    restart: unless-stopped
    build: ./upload/
    ports:
      - "127.0.0.1:3008:8080"
    volumes:
      - ${UPLOAD_DIR}:/go/src/app/upload
    #    logging:
    #      driver: none
    environment:
      CHECK_URL: ${CHECK_URL}
      PROXY_API: ${PROXY_API}